version: "0.1"

services:
  database:
    image: postgres:14-alpine
    container_name: "postgres"
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "HYgTN_W6dL7KyG7"
      POSTGRES_DB: "pogo-connect-dev"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-d", "pogo-connect-dev" ]
#      interval: 30s
#      timeout: 60s
#      retries: 3
#      start_period: 80s

  backend:
#    profiles: [ "api" ]
    build:
      context: .
    ports:
      - 3002:3002
#    environment:
#      HOST: postgres:5432
#      PORT: 3002
    depends_on:
      - database
#      database:
#        condition: service_healthy
