name: Setup Node.js environment
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker
        run: docker-compose build

      - name: Run tests
        run: docker-compose run backend yarn test
